### ISSUE TITLE
Totara 11 fatal php error during unit test: Fatal error: Cannot declare class reminder, because the name is already in use in /var/www/site/lib/reminderlib.php on line 291

### ISSUE THREAD

**Issue by kristian-94** [isuru89/moodle-reminders-for-calendar-events#25]
1. Install a clean totara 11, and install this plugin. Check out the REMINDERS_34 branch. 
2. Run `php admin/tool/phpunit/cli/init.php`
3. Run `vendor/bin/phpunit`
4. After a few seconds you will see the error: 
>Fatal error: Cannot declare class reminder, because the name is already in use in /var/www/site/lib/reminderlib.php on line 291

The problem is that unlike moodle, totara has a class called reminder as well, in lib/reminderlib.php.
Looks like this is a problem across all totara and plugin versions, since the plugin and totara both declare this class in most versions. 
Will need to change this class name.

**Comment by danmarsden** [comment]
Just a comment to say this is actually a failure against moodle coding guidelines - all classes should be namespaced or use the frankenstyle prefix - which in this case would be local_reminder - not just "reminder" - typically this would get picked up in our review process for new plugins submitted to the plugins db, but this plugin has been around a lot longer than that! :-)

@isuru89 - thanks for your work maintaining this plugin!! :-)

**Comment by isuru89** [comment]
@danmarsden  @kristian-94  Will rename this class in next version and also will release soon

**Comment by kristian-94** [comment]
@isuru89  Hi, has the next release come out yet?

**Comment by isuru89** [comment]
@kristian-94 started working on it.
**Progress**: https://github.com/isuru89/moodle-reminders-for-calendar-events/tree/task/fix-to-local-class-names

**Comment by isuru89** [comment]
Fixed in v1.7
