### ISSUE TITLE
Possible duplicate notifications caused by duplicate cron config

### ISSUE THREAD

**Issue by jtsafran** [isuru89/moodle-reminders-for-calendar-events#26]
Hi there!

It looks like when the new scheduled task code was added, the name of the function was not changed from local_reminders_cron (https://github.com/isuru89/moodle-reminders-for-calendar-events/blob/master/lib.php#L70).  That is causing it to be called by the admin cron, as well as the new scheduled task and can lead to duplicate notifications since the cron locks would not work when being called in two different ways. 

I see someone else has reported a similar issue here https://tracker.moodle.org/browse/CONTRIB-3647.

**Comment by isuru89** [comment]
Thank you for reporting. I will be fixing it soon.

**Comment by isuru89** [comment]
Fixed in v1.7
