### ISSUE TITLE
Emails being sent to suspended users

### ISSUE THREAD

**Issue by davefoord** [isuru89/moodle-reminders-for-calendar-events#27]
At the moment, if a user is manually enrolled on the course, but their enrolment is suspended, it still sends an email notification to them, even though they are suspended. It would better not to send the email to suspended users.

Steps to test.

Create a course, enrol 5 users A,B,C,D and E
Create a course event and check that all get email.
Create an event in the future.
Suspend A at course level.
Check that the other 4 get emails, but A doesn't.
Create an event in the future.
Suspend B at course level.
Check that C,D and E get emails, but A & B don't.
Create an event in the future.
Unsuspend A and B, check that they do now get the emails.

**Comment by isuru89** [comment]
Fixed in v1.7

**Comment by lorenagarcia-moodle** [comment]
Hello @isuru89 ,

I wanted to let you know that we’ve noticed the Reminders plugin (version 2.7.3) has started sending notifications to suspended users or users with expired enrollments, even though it didn’t do this before.

Steps to test:

- Create a course and enroll user A and user B.
- Suspend user A in the course.
- Expire the enrollment of user B in the course.
- Create a future event in the course.
- Check that both A and B receive a notification for the event, even though their enrollment is no longer active.

Thank you so much for your help.

Best, 
Lorena
