### ISSUE TITLE
Add ability to send out notifications after assignments' due date

### ISSUE THREAD

**Issue by evandonovan** [isuru89/moodle-reminders-for-calendar-events#3]
We have a strong need at my college (City Vision College) to be able to send out reminders to students who have not yet submitted assignments after the assignments' due date, so that they will not lose points for late submission.

How difficult do you think it would be to implement this as a feature? I imagine it could just check for the assignments on the calendar, but then send out the notification only if there wasn't yet a record in the assignment_submissions table.

I may be implementing this soon, although I would need more familiarity with the code, but was curious if this was something you would consider.

**Comment by isuru89** [comment]
This feature has been shipped with v2
