### ISSUE TITLE
Error on new M3.6 installation

### ISSUE THREAD

**Issue by demontech** [isuru89/moodle-reminders-for-calendar-events#66]
Hi,

I'm installing the newest version 2020041200 on Moodle 3.6 with php 7.0 , and I'm getting this error when installing:

![image](https://user-images.githubusercontent.com/8148238/79189396-7c4b3b80-7dd6-11ea-8a2d-8873d732b769.png)

Thanks

**Comment by isuru89** [comment]
@demontech This is due to plugin runs on php7.1+.

However since this plugin can be run on Moodle 3.5, I will be making this to work on php7.0+ too.

**Comment by isuru89** [comment]
This will be released in v2.1.2

**Comment by isuru89** [comment]
Released with 2.1.2 (2020041500)
