### ISSUE TITLE
Minor issue with 'coursecat' class

### ISSUE THREAD

**Issue by saritaphoo** [isuru89/moodle-reminders-for-calendar-events#76]
Getting a warning for 'coursecat' being deprecated but it is still used in locallib.php

**Comment by isuru89** [comment]
@saritaphoo Could you please answer below. 

1. Which moodle version are you using? 
2. Any stacktrace you got?
3. Reproducible steps?

**Comment by saritaphoo** [comment]
I am using Moodle 3.8. Below is the stacktrace. 
<img width="1167" alt="Screen Shot 2020-05-12 at 1 50 29 PM" src="https://user-images.githubusercontent.com/26909500/81744594-49897700-9458-11ea-85bc-b2460c5a3c3c.png">

I installed the zip reminder plugin file through plugin and got this after confirming installation.

**Comment by isuru89** [comment]
@saritaphoo 
Thank you. Will look into this as it seems Moodle 3.6+ onwards, this coursecat class has been deprecated. 
Will be fixing sooner. However I hope that you still can continue using plugin for other reminder types
