### ISSUE TITLE
Possible duplicate notifications caused by duplicate cron config happening in v2.2

### ISSUE THREAD

**Issue by jtsafran** [isuru89/moodle-reminders-for-calendar-events#91]
See https://github.com/isuru89/moodle-reminders-for-calendar-events/issues/26.  Looks like this has come back in v2.2.  Line https://github.com/isuru89/moodle-reminders-for-calendar-events/blob/master/lib.php#L87.  

Since this is the old cron naming convention, this cron will be triggered both by the admin cron as well as the new scheduled task, causing duplicate mailings if they run close enough together.

**Comment by isuru89** [comment]
Fixed with release v2.2.2
