### ISSUE TITLE
Release for 3.9?

### ISSUE THREAD

**Issue by InFerYes** [isuru89/moodle-reminders-for-calendar-events#96]
Can this plugin be released for 3.9 or are there any important changes to the new Moodle version that prevents this?

**Comment by isuru89** [comment]
@InFerYes 
As far as I know, the latest version should work as it is. But let me know any issues faced

**Comment by isuru89** [comment]
Release for moodle v3.9 has been released with plugin v.2.2.3 
Please check here
https://moodle.org/plugins/pluginversions.php?plugin=local_reminders
